name: Build Multi-Platform Docker Image

on:
  push:
    branches: ["main"]

env:
  IMAGE_NAME: olhaya/hello-app

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "linux/amd64"
            os: "linux"
            arch: "amd64"
            base_image: "alpine:3.18"
          - platform: "linux/arm64"
            os: "linux"
            arch: "arm64"
            base_image: "alpine:3.18"
          - platform: "windows/amd64"
            os: "windows"
            arch: "amd64"
            base_image: "mcr.microsoft.com/windows/nanoserver:ltsc2022"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          build-args: |
            TARGETOS=${{ matrix.os }}
            TARGETARCH=${{ matrix.arch }}