name: Build and Push Multiarch Docker Image

on:
  push:
    branches: [main]

jobs:
  build-linux:
    name: Build and push Linux multiarch image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Linux multiarch image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: olhaya/os-greeter:linux

          build-args: |
            BASE_IMAGE=python:3.12-slim

  build-windows:
  name: Build and push Windows image
  runs-on: windows-latest
  steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Windows image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: olhaya/os-greeter:windows-amd64
        platforms: windows/amd64
        build-args: |
          BASE_IMAGE=mcr.microsoft.com/windows/nanoserver:ltsc2022


  manifest:
    name: Create and push multiarch manifest
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Create and push manifest
        run: |
          docker manifest create olhaya/os-greeter:latest \
            --amend olhaya/os-greeter:linux \
            --amend olhaya/os-greeter:windows-amd64

          docker manifest push olhaya/os-greeter:latest
