name: Build Multi-Platform Docker Image

on:
  push:
    branches: ["main"]

env:
  IMAGE_NAME: olhaya/hello-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,windows/amd64
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          build-args: |
            TARGETOS=linux
            TARGETARCH=amd64