name: Build and Push Multiarch Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push multiarch image (Linux only due to GitHub limitations)
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: olhaya/os-greeter:latest
          platforms: linux/amd64,linux/arm64
          build-args: |
            BASE_IMAGE=python:3.12-slim
